

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      # - CHOKIDAR_USEPOLLING=true

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - "DEBUG=1"
    depends_on:
      - db

  tailwind:
    image: node:18-slim # Or a specific tailwind image
    working_dir: /app
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    # This runs your exact command inside the container
    # command: >
    #   sh -c "npm install && 
    #          npx tailwindcss -i ./static/src/input.css -o ./static/dist/styles.css --watch --poll 100"
    # environment:
    #   - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data: