from django.urls import path

from .views import (
    IngredientListView,
    IngredientCreateView,
    IngredientDetailView,
    IngredientDeleteView,
    IngredientUpdateView,
    PurchaseListView,
    PurchaseCreateView,
    PurchaseDetailView,
    PurchaseUpdateView,
    PurchaseAdjustmentListView,
    PurchaseAdjustmentCreateView,
    InventoryHomeView,
)

app_name = "inventory"

urlpatterns = [
    path(
        "",
        InventoryHomeView.as_view(),
        name="index",
    ),
    path(
        "ingredients/list",
        IngredientListView.as_view(),
        name="list",
    ),
    path(
        "ingredient/create/",
        IngredientCreateView.as_view(),
        name="create",
    ),
    path(
        "ingredient/<uuid:pk>/",
        IngredientDetailView.as_view(),
        name="ingredient",
    ),
    path(
        "ingredient/<uuid:pk>/delete/",
        IngredientDeleteView.as_view(),
        name="delete",
    ),
    path(
        "ingredient/<uuid:pk>/update/",
        IngredientUpdateView.as_view(),
        name="update",
    ),
    path(
        "ingredient/<uuid:pk>/purchase/list/",
        PurchaseListView.as_view(),
        name="purchase_list",
    ),
    path(
        "ingredient/<uuid:pk>/purchase/create/",
        PurchaseCreateView.as_view(),
        name="purchase_create",
    ),
    path(
        "ingredient/<uuid:pk>/purchase/",
        PurchaseDetailView.as_view(),
        name="purchase",
    ),
    path(
        "ingredient/<uuid:pk>/purchase/update/",
        PurchaseUpdateView.as_view(),
        name="purchase_update",
    ),
    path(
        "ingredient/<uuid:pk>/purchase/adjustment/list",
        PurchaseAdjustmentListView.as_view(),
        name="adjustment_list",
    ),
    path(
        "purchase/<uuid:pk>/purchase/adjustment/create/",
        PurchaseAdjustmentCreateView.as_view(),
        name="adjustment_create",
    ),
]
