# Generated by Django 6.0.4 on 2026-06-03 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_ingredient_price_alter_ingredient_stock_qty'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDraftIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.recipedraft')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
            ],
        ),
    ]
