# Generated by Django 6.0.4 on 2026-07-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionbatch',
            name='produced_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
