# Generated by Django 6.0.4 on 2026-06-04 04:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_recipedraft_recipedraftingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedraft',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
