# Generated by Django 6.0.4 on 2026-07-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_productionbatch_produced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
