# Generated by Django 6.0.4 on 2026-06-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_recipedraft_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipedraftingredient',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='recipedraftingredient',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RecipeDraft',
        ),
        migrations.DeleteModel(
            name='RecipeDraftIngredient',
        ),
    ]
