# Generated by Django 6.0.4 on 2026-07-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_productionbatch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionbatch',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('c', 'Complete'), ('d', 'Disabled')], default='p', max_length=1),
        ),
    ]
