# Generated by Django 6.0.4 on 2026-06-16 04:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_recipeingredient_quantity_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity_needed',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Quantity must be greater than or equal to 0.01.')]),
        ),
    ]
