# Generated by Django 6.0.4 on 2026-07-08 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0007_alter_productionbatch_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionbatch",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="batches",
                to="production.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="productionbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("p", "Pending"),
                    ("c", "Complete"),
                    ("d", "Disabled"),
                    ("i", "In Progress"),
                ],
                default="p",
                max_length=1,
            ),
        ),
    ]
