# Generated by Django 6.0.4 on 2026-06-16 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_recipeingredient_quantity_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(error_messages={'blank': 'Recipe name cannot be empty.'}, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_requirements', to='production.recipe'),
        ),
    ]
