# Generated by Django 6.0.4 on 2026-07-08 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0008_alter_productionbatch_recipe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionbatch",
            name="recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batches",
                to="production.recipe",
            ),
        ),
    ]
