# Generated by Django 6.0.4 on 2026-07-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_alter_productionbatch_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionbatch',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('I', 'In Progress'), ('C', 'Complete'), ('X', 'Cancelled')], default='P', max_length=1),
        ),
    ]
