# Generated by Django 6.0.4 on 2026-06-16 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ingredient_unit'),
        ('production', '0009_alter_recipe_name_alter_recipeingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(error_messages={'blank': 'Recipe name cannot be blank.', 'max_length': 'Max characters for recipe name: 100'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(error_messages={'blank': 'Must have at least 1 ingredient.'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient'),
        ),
    ]
