# Generated by Django 6.0.4 on 2026-06-16 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ingredient_unit'),
        ('production', '0010_alter_recipe_name_alter_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(error_messages={'blank': 'Must have at least 1 ingredient.'}, through='production.RecipeIngredient', to='inventory.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient'),
        ),
    ]
