# Generated by Django 6.0.4 on 2026-07-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0010_alter_productionbatch_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productionbatch",
            old_name="produced_at",
            new_name="created_at",
        ),
    ]
