# Generated by Django 6.0.4 on 2026-06-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ingredient_unit'),
        ('production', '0011_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='production.RecipeIngredient', to='inventory.ingredient'),
        ),
    ]
