# Generated by Django 6.0.4 on 2026-07-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_rename_produced_at_productionbatch_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionbatch',
            old_name='batches',
            new_name='batch_qty',
        ),
    ]
