# Generated by Django 6.0.4 on 2026-07-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_rename_batches_productionbatch_batch_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionbatch',
            name='batch_qty',
            field=models.IntegerField(),
        ),
    ]
