# Generated by Django 6.0.4 on 2026-07-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_alter_productionbatch_batch_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchingredient',
            old_name='quantity_used',
            new_name='qty_used',
        ),
    ]
