# Generated by Django 6.0.4 on 2026-07-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_rename_quantity_used_batchingredient_qty_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantity_needed',
            new_name='qty_needed',
        ),
    ]
