# Generated by Django 6.0.4 on 2026-07-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0016_productionbatch_cancellation_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionbatch",
            name="started_at",
            field=models.DateTimeField(null=True),
        ),
    ]
