# Generated by Django 6.0.4 on 2026-06-26 09:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='stock_qty',
            new_name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='price',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams'), ('ml', 'Mililiters')], default='g', max_length=2),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IngredientPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateField()),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('qty_purchased', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'), message='Quantity cannot be less than zero.')])),
                ('qty_remaining', models.DecimalField(decimal_places=1, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.ingredient')),
            ],
        ),
    ]
