# Generated by Django 6.0.4 on 2026-07-01 11:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientpurchase",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.01"), message="Must be at least 0.01."
                    )
                ],
            ),
        ),
    ]
