# Generated by Django 6.0.4 on 2026-07-03 04:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_ingredientpurchase_total_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredientpurchase",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ingredientpurchase",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
