# Generated by Django 6.0.4 on 2026-06-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_stock_qty_ingredient_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientpurchase',
            name='qty_remaining',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
