# Generated by Django 6.0.4 on 2026-06-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_ingredient_price_alter_ingredient_stock_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams'), ('ml', 'Mililiter')], default='g', max_length=2),
        ),
    ]
