# Generated by Django 6.0.4 on 2026-07-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ingredientpurchase_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientpurchase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
