# Generated by Django 6.0.4 on 2026-07-03 04:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_ingredientpurchase_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientpurchase",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
