# Generated by Django 6.0.4 on 2026-06-19 04:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_ingredient_stock_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=6, validators=[django.core.validators.MinValueValidator(1, message='Price cannot be less than 0.01')]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='stock_qty',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='Stock quantity cannot be less than 0.01.')]),
        ),
    ]
