# Generated by Django 6.0.4 on 2026-06-19 04:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_ingredient_price_alter_ingredient_stock_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'), message='Price cannot be less than 0.01')]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='stock_qty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'), message='Stock quantity cannot be less than 0.01.')]),
        ),
    ]
