# Generated by Django 6.0.4 on 2026-06-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_ingredient_price_alter_ingredient_stock_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(error_messages={'blank': 'Ingredient name cannot be blank.', 'max_length': 'Ingredient name cannot exceed 100 characters.', 'null': 'Ingredient name cannot be blank.'}, max_length=100),
        ),
    ]
