# Generated by Django 6.0.4 on 2026-07-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_purchaseadjustment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseadjustment",
            name="note",
            field=models.CharField(max_length=500),
        ),
    ]
