# Generated by Django 6.0.4 on 2026-08-07 14:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_ingredient_created_at_ingredient_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='Stock threshold cannot be negative.')]),
        ),
        migrations.AlterField(
            model_name='ingredientpurchase',
            name='qty_purchased',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Purchased quantity must be at least 0.01.')]),
        ),
        migrations.AlterField(
            model_name='ingredientpurchase',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Total cost must be at least 0.01.')]),
        ),
    ]
